import React from 'react';
import Layout from './../components/Layout';
import '../scss/pages/PrivacyPolicy.scss';

const PrivacyPolicy = () => {

   
  return (
    <Layout>
        <div className="privacy-policy-page">
            <div className='content-div'>
                <h2>eaconomy™ Privacy Policy</h2>               
                
                <p><span >Thank you for using eaconomy!</span></p>
                <p><span >eaconomy ("eaconomy", "us", "we", or "our") operates <a href="/home">https://www.eaconomy.best</a> (the "Site") and the services provided as part of a subscription membership with eaconomy™ (the "Services"). When we refer to "you" or to a "customer," "member," or "subscriber," we mean any past, current or prospective customer of eaconomy™, including any visitor to our site.</span></p>
                <p><span >This privacy statement has been created in order to demonstrate our firm and continuing commitment to the privacy of personal information provided by those visiting and interacting with this website. We hold the privacy of your personal information in the highest regard. The following discloses our information gathering and dissemination practices for this website. This privacy policy outlines how we collect, use, process, and disclose your information, including personal information, in conjunction with your access to and use of our platform.</span></p>
                <p><span >Please read this Policy to learn more about the ways in which we collect and use your information. If we make any material changes to this Policy, we will notify you in accordance with the process described in the "Revisions or Changes" section of this Policy, below. By using our Services, you consent to our collection, use, and disclosure of your information as described in this Policy.</span></p>
                <p><strong><u><span >Sole Data Controller</span></u></strong></p>
                <p><span >eaconomy™ is the sole "data controller." We only have access to and/or collect information that you voluntarily give us via email or other means of direct contact with you.</span></p>
                <p><span >We will not sell, rent, lend or lease this information to anyone.</span></p>
                <p><span >We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order.</span></p>
                <p><span >Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy. You will find our contact information at the end of this privacy agreement.</span></p>
                <p><strong><u><span >Information We Collect</span></u></strong></p>
                <p><span >Personal Information: This is information that you voluntarily provide when you perform one of the following actions; register with eaconomy™, fill in a form, subscribe to a newsletter, place an order, speak via phone or correspond via live chat or email with us. This information is typically but not limited to; name, address, telephone number, e-mail address, credit card information, billing address and shipping information.</span></p>
                <p><span >"Device" Information: This is aggregate information that includes but is not limited to demographic information, IP addresses, user behavior data from web interaction metrics tools and other information that does not reveal your specific identity. This information allows us to respond to your inquiries, provide you with services you have requested, keep you informed of services we think may be of interest to you, personalize your experience with the site, and other reasons.</span></p>
                <p><span >We collect Device Information using the following technologies:</span></p>
                <p><span >"Log Files" track actions occurring on the Site, and collect data including your IP address, browser type, Internet service provider, referring/exit pages, and date/time stamps.</span></p>
                <p><span >Like many sites, we use "cookies" to collect information and differentiate computers from one another. In some cases, cookies are used to prevent you from having to log in more than is necessary for security. Cookies, in conjunction with our web server's log files, allow us to calculate the aggregate number of people visiting the company website and which parts of the site are most popular.</span></p>
                <p><span >This helps us gather feedback to constantly improve the website. Cookies do not allow us to gather any personal information about you and we do not intentionally store any personal information that your browser provided to us in your cookies.</span></p>
                <p><span >You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Site.</span></p>
                <ul><li><a href="https://support.microsoft.com/en-us/products/windows" target="_blank"><span >Cookie settings in Internet Explorer</span></a></li><li><a href="https://support.mozilla.org/en-US/kb/cookies" target="_blank"><span >Cookie settings in Firefox</span></a></li><li><a href="https://support.google.com/chrome/answer/95647?hl=en" target="_blank"><span >Cookie settings in Chrome</span></a></li><li><span ><a href="https://support.apple.com/kb/PH5042?locale=en_GB" target="_blank">Cookie settings in Safari web</a> and <a href="https://support.apple.com/en-gb/HT201265" target="_blank">iOS</a></span></li></ul><p><span >For more information about cookies, and how to disable cookies, visit <a href="http://www.allaboutcookies.org/" target="_blank">http://www.allaboutcookies.org</a>.</span></p>
                <p><span >"Cookies" are data files that are placed on your device or computer and often include an anonymous unique identifier. Cookies are sent to your browser from a web site and stored on your computer's hard drive.</span></p>
                <p><span >"Web beacons," "tags," and "pixels" are electronic files used to record information about how you browse the Site.</span></p>
                <p><span >IP addresses are used by your computer every time you are connected to the Internet. Your IP address is a number that is used by computers on the network to identify your computer. IP addresses are automatically collected by our web server as part of demographic and profile data known as traffic data so that data (such as the web pages you request) can be sent to you.</span></p>
                <p><span >We may collect analytics data, or use third-party analytics tools such as Google Analytics, to help us measure traffic and usage trends and to understand more about the demographics of our users. You can learn more about Google's practices at <a href="https://policies.google.com/privacy/partners" target="_blank">https://policies.google.com/privacy/partners</a>, and view its currently available opt-out options at.</span></p>
                <p><strong><u><span >Do Not Track</span></u></strong></p>
                <p><span >Please note that we do not alter our Site’s data collection and use practices when we see a Do Not Track signal from your browser.</span></p>
                <p><strong><u><span >How Do We Use Your Personal Information?</span></u></strong></p>
                <p><span >We use the registration and order Information that we collect generally to fulfill any services or orders placed through the Site (including processing your payment information, arranging for shipping, and providing you with invoices and/or order confirmations).</span></p>
                <p><span >Additionally, we may use this Order Information to:</span></p>
                <ul><li><span >Communicate with you</span></li><li><span >Screen our orders for potential risk or fraud</span></li><li><span >When in line with the preferences you have shared with us, provide you with information or advertising relating to our products or services</span></li></ul><p><strong><u><span >Account Information</span></u></strong></p>
                <p><span >As a member, you are required to create an account. You testify that the information you provide is truthful and accurate, and that you are not impersonating another person. You are responsible for maintaining the confidentiality of any password you may use to access your account, and you agree not to transfer your password or username, or lend or otherwise transfer your use of or access to your account, to any third party. You agree to immediately notify us of any unauthorized use of your password or username or any other breach of security related to your account. You agree that eaconomy™ is not liable, and you will hold eaconomy™ harmless, for any loss or damage arising from your failure to comply with any of the foregoing obligations.</span></p>
                <p><strong><u><span >Your Access to and Control Over Your Information</span></u></strong></p>
                <p><span >The personal information that we have on file for you is the same information that you have provided in your account or have submitted to us when participating in surveys, contests or requesting additional information or services. You can opt out of any of these lists using the links provided in the media or you can send an email to us with your request. </span></p>
                <p><span >We will try and respond to your request promptly and in all cases within 30 days. To protect customer privacy and security, we reserve the right to take reasonable steps to verify a customer's identity prior to granting access to or processing changes or corrections to such information.</span></p>
                <p><strong><u><span >EU Citizens, Your Rights</span></u></strong></p>
                <p><span >If you are a European resident, you have the right to access personal information we hold about you and to ask that your personal information be corrected, updated, or deleted. If you would like to exercise this right, please contact us through the "Contact Us" section in this policy. </span></p>
                <p><span >Additionally, if you are a European resident we note that we are processing your information in order to fulfill contracts we might have with you (for example if you make an order through the Site), or otherwise to pursue our legitimate business interests listed above. Additionally, please note that your information will be transferred outside of Europe, including to Canada and the United States.</span></p>
                <p><strong><u><span >Data Retention</span></u></strong></p>
                <p><span >When you place an order through the Site, we will maintain your Order Information for our records unless and until you ask us to delete this information.</span></p>
                <p><strong><u><span >Surveys and Contests</span></u></strong></p>
                <p><span >From time-to-time our site requests information via surveys or contests. Participation in these surveys or contests is completely voluntary and you may choose whether or not to participate and therefore disclose this information. Information requested may include contact information (such as name and shipping address), and demographic information (such as zip code, age level). Contact information will be used to notify the winners and award prizes. Survey information will be used for purposes of monitoring or improving the use and satisfaction of this site.</span></p>
                <p><strong><u><span >Children</span></u></strong></p>
                <p><span >Children are not eligible to use our services unsupervised and we ask that children (under the age of 14) do not submit any personal information to us. If you are a minor, you can use our services only in conjunction with permission and guidance from your parents or guardians.</span></p>
                <p><strong><u><span >Use of Testimonies and Reviews</span></u></strong></p>
                <p><span >We may select and post customer testimonials and/or reviews regarding our services, which may contain personally identifiable information such as your name and/or the city, state, or country in which you live. We will obtain your consent prior to posting any testimonial with your name. If you post such content, it will be available to other users of the services. Your posting may also become public and we cannot prevent such information from being used in a manner that may violate this Policy or the law. If you would like us to remove or delete your name or testimonial from our Services, you may contact us using the information in the "Contact Us" section of this Policy. Note that copies of information that you have updated, modified, or deleted may remain viewable in cached and archived pages of our site for a period of time.</span></p>
                <p><strong><u><span >Links</span></u></strong></p>
                <p><span >This website contains links to other sites. Please be aware that we are not responsible for the content or privacy practices of such other sites. We encourage our users to be aware when they leave our site and to read the privacy statements of any other site that collects personally identifiable information. We disclaim any responsibility for the security of any information (including without limitation credit card and personally identifiable information personal information) that you may provide to any third party. </span></p>
                <p><span >It is possible that some of the links on our site that go to a third party site with a service or product could result in eaconomy™ earning a commission.</span></p>
                <p><strong><u><span >Security</span></u></strong></p>
                <p><span >We use reasonable and diligent efforts to maintain accurate information on our customers, and have adopted and implemented reasonable industry standard security procedures to protect any such information collected. When you submit sensitive information via the website, your information is protected both online and offline.</span></p>
                <p><span >Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a lock icon in the address bar and looking for "https" at the beginning of the address of the Web page.</span></p>
                <p><span >While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.</span></p>
                <p><strong><u><span >Referring People</span></u></strong></p>
                <p><span >If you choose to use our referral feature to share with a friend our Services, we will ask you for your friend's name and email address. We will use the information you provide to automatically send your friend an email inviting him or her to visit our site. Your friend can opt out of receiving future promotional/marketing messages from us by clicking the "Unsubscribe" link found in the footer of our email messages. Your friend may also contact us using the information in the "Contact Us" section of this Policy, and request that we remove their information from our database. Treatment of your friend's information will be subject to the terms of this Policy.</span></p>
                <p><strong><u><span >EN-US and Swiss-US Privacy Shield Frameworks</span></u></strong></p>
                <p><span >We comply with the EU-US Privacy Shield Framework and the Swiss-US Privacy Shield Framework as set forth by the US Department of Commerce regarding the collection, use, and retention of personal information transferred from European Union and Switzerland to the United States, respectively. We have certified to the Department of Commerce that it adheres to the Privacy Shield Principles. If there is any conflict between the policies in this privacy policy and the Privacy Shield Principles, the Privacy Shield Principles shall govern.</span></p>
                <p><span >To learn more about the Privacy Shield program, and to view our certification page, please visit <a href="http://www.privacyshield.gov/" target="_blank">www.privacyshield.gov</a>. For full definitions of the Privacy Shield Principles, please visit <a href="http://www.privacyshield.gov/EU-US-Framework." target="_blank">www.privacyshield.gov/EU-US-Framework</a></span></p>
                <p><span >Under the Privacy Shield, you have the right to access, correct, or delete your personal data. You also have the right to limit our use of your data – including the right to opt-in or out of receiving communications. To exercise any of these rights, please send an email to <a href="mailto:legal@eaconomy.io" target="_blank">legal@eaconomy.io</a>.</span></p>
                <p><strong><u><span >Disclosure</span></u></strong></p>
                <p><span >We may disclose personal information when legally compelled to do so, in other words, when we, in good faith, believe that the law requires the information or for the protection of our legal rights. We may also disclose account information when the company has reason to believe that disclosing this information is necessary to identify, contact or bring legal action against someone who may be violating the Terms of Service or to protect the safety of other clients and the Public.</span></p>
                <p><strong><u><span >Acquisitions or Changes in Ownership</span></u></strong></p>
                <p><span >In the event that the company website (or a substantial portion of its assets) is acquired, your information would be considered part of those assets, and may be part of those assets that are transferred.</span></p>
                <p><strong><u><span >Revisions and Changes</span></u></strong></p>
                <p><span >This Privacy Policy is effective as of the date listed at the beginning of this policy and will remain in effect except with respect to any changes in its provisions in the future, which will be in effect immediately after being posted on this page.</span></p>
                <p><span >We reserve the right to update or change our Privacy Policy at any time and you should check this Privacy Policy periodically. Your continued use of the Service after we post any modifications to the Privacy Policy on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.</span></p>
                <p><span >If we make any material changes to this Privacy Policy, we will notify you either through the email address you have provided us, or by placing a prominent notice on our website.</span></p>
                <p><strong><u><span >Contact Us</span></u></strong></p>
                <p><span >For more information about our privacy practices, if you have questions, or if you would like to make a complaint, please contact us by email at </span><span ><a href="mailto:support@eaconomy.com">support@eaconomy.com</a> or by mail using the details provided below:</span></p>
                <p><span >1980 Festival Plaza Drive Summerlin South, #300</span></p>
                <p><span >Las Vegas, NV, 89135</span></p>
                <p><span >United States of America</span></p>


                
                 
               
            </div>

        </div>
    </Layout>
  );
};

export default PrivacyPolicy;
