import React from 'react';
import Layout from './../components/Layout';
import '../scss/pages/TermsAndConditions.scss';

const TermsAndConditions = () => {

   
  return (
    <Layout>
        <div className="tac-page">
            <div className='content-div'>
                <h2>Terms and Conditions</h2>               
                   
            
                <p><span >These Terms and Conditions, in their present form and as amended from time to time at the discretion of eaconomy™, are incorporated into the eaconomy™ Independent Software Partner User Agreement. They are the terms and conditions of the Independent Software Partner's contract with eaconomy™. It is the responsibility of each Independent Software Partner to read, understand, adhere to, and ensure that he/ she is aware of and operating under the most current version of these Terms and Conditions. You must also comply with the description of the Rewards Plan and honor all applicable laws in the country in which you operate your eaconomy™ business. The words "company" and "eaconomy", when used in these documents, refer to eaconomy™, and the term "ISP" means "Independent Software Partner". An Independent Software Partner is an independent contractor, not an employee of the company.</span></p>
                <p><span >The purpose of the Independent Software Partner Agreement is: to deﬁne the relationship between the company and the ISP; to set standards of acceptable business behavior; to assist ISP in building and protecting their business.</span></p>
                <p><strong><u><span >Changes</span></u></strong></p>
                <p><span >The Company may from time to time amend the terms and conditions of the ISP User Agreement, Terms and Conditions, Rewards Plan and Software Price List. Amendments shall be effective upon notiﬁcation of the changes in ofﬁcial eaconomy™ publications, website(s), and/or electronic notiﬁcations distributed to all active ISPs.</span></p>
                <p><strong><u><span >Consequences of Delays, Closures and Platform Set Up Mistakes</span></u></strong></p>
                <p><span >The company shall not be responsible for delays and failures in performing its obligations due to circumstances beyond its reasonable control, such as strikes, labor difﬁculties, riots, war, ﬁre, death, curtailment or interruption of a source of supply, government decrees or orders, cyber hacking, currency exchange issues, ﬁat currency trading platform temporary shutdowns and/or closures, the consequences of an ISP clicking the YES/ON button on the trading platforms for withdrawing ﬁat currencies, and any other trading platform set up mistakes made by the ISP in direct conﬂict with company trainings and guidelines, etc. Policies and</span></p>
                <p><strong><u><span >Provisions Severable</span></u></strong></p>
                <p><span >If any provision of the Independent Software Partner User Agreement as it currently exists or as may be amended is found to be invalid, illegal, or unenforceable for any reason, only the invalid provision will be severed from the Independent Software Partner User Agreement; the remaining terms and provisions shall remain in full force and effect and shall be construed as if such invalid, illegal, or unenforceable provision never comprised a part of the Independent Software Partner User Agreement.</span></p>
                <p><strong><u><span >Titles Not Substantive</span></u></strong></p>
                <p><span >The titles and headings to these Terms and Conditions are for reference purposes only and do not constitute, and shall not be construed as, substantive terms of the Independent Software Partner User Agreement.</span></p>
                <p><strong><u><span >Waiver</span></u></strong></p>
                <p><span >The company never forfeits its right to require ISP compliance with the Independent Software Partner User Agreement or with applicable laws and regulations governing business conduct. Only in rare circumstances will a policy be waived, and the Compliance Ofﬁcer or an ofﬁcer of the company will convey such waivers in writing. The waiver will apply only to that speciﬁc case.</span></p>
                <p><strong><u><span >Becoming an ISP</span></u></strong></p>
                <p><span >The requirements to become an ISP: Be at least the age of majority in your country of residence; reside in a geographic area where eaconomy™ has been approved for business; fully read and accept the company's Terms and Conditions, Full Rewards Plan, Income Disclaimers, Independent Software Partner Agreement, Terms of Use, Privacy Policy and Refund Policy; as an independent contractor, assume all appropriate responsibilities for accounting for income tax, insurances and expenses to support your business. The company reserves the right to accept or reject any application for any reason.</span></p>
                <p><strong><u><span >Username Identiﬁcation and ISP Number</span></u></strong></p>
                <p><span >When the company receives and accepts a new ISP account registration, the company will assign a unique ISP Number to that Independent Software Partner. ISP must use their ISP Number whenever they communicate with a company representative regarding business matters.</span></p>
                <p><strong><u><span >ISP Beneﬁts</span></u></strong></p>
                <p><span >Once the company accepts an Independent Software Partner Application and Agreement, the beneﬁts of the Rewards Plan and the Independent Software Partner Agreement are available to the new ISP.</span></p>
                <p><span >These beneﬁts include the right to purchase company software products and services; participate in the company Rewards Plan (receive bonuses and commissions, if eligible); sponsor other individuals as Customers or ISP into the company business and thereby build a Downline Organization and progress through the company Rewards Plan; receive company literature and other company communications; participate in company-sponsored support, service, training, motivational, and recognition functions upon payment of appropriate charges, if applicable; participate in promotional and incentive contests and programs sponsored by eaconomy™ for its ISPs; ISP may retail eaconomy™ software products or services and proﬁt from these sales. Operating as an Independent Software Partner Actions of Household Members or Afﬁliated Individuals - If any member of an ISP's immediate household engages in any activity, which, if performed by the ISP would violate any provision of the Independent Software Partner User Agreement, such activity will be deemed a violation by the ISP.</span></p>
                <p><u><strong><span >Adherence to the company Rewards Plan</span></strong></u></p>
                <p><span >An ISP must adhere to the terms of the company Rewards Plan as set forth in ofﬁcial company literature or ofﬁcial company website(s). ISP shall not offer the company opportunity through or in combination with, any other opportunity or unapproved method of marketing (unless approved by the company Corporate or Compliance Department). ISP shall not require or encourage other current or prospective Customers or ISPs to participate in the company in any manner that varies from the program as set forth in ofﬁcial company literature. ISP shall not require or encourage other current or prospective Customers or ISPs to execute any agreement or contract other than ofﬁcial ofﬂine or online company agreements and contracts in order to become an ISP. Similarly, ISP shall not require or encourage other current or prospective Customers or ISPs to make any purchase from, or payment to, any individual or other entity to participate in the company Rewards Plan, other than those purchases or payments identiﬁed as recommended or required in ofﬁcial company literature or ofﬁcial company websites(s).</span></p>
                <p><strong><u><span >Advertising In general</span></u></strong></p>
                <p><span >ISP must avoid all discourteous, deceptive, misleading, illegal, unethical, or immoral conduct or practices in their marketing and promotion of eaconomy™, the company opportunity, the Rewards Plan, and company software products. No ISP may produce unauthorized sales, marketing, and support materials to market or promote the company, the company opportunity, the Rewards Plan, company's products, or their company businesses (unless approved by company Corporate or Compliance Department in writing).</span></p>
                <p><span >All ISP may only use sales aids and support materials produced or currently approved by the company. Sales, marketing and support materials include, but are not limited to, training and recruiting information, brochures, ﬂyers, pamphlets, posters, postcards, letters, classiﬁed advertisements, etc. promoting the company's software products and services, as well as e-mail messages, voicemail message recordings, and Internet Websites used to publicize the company, its software products, services, or Rewards Plan. If ISP does use his/her own materials or marketing methods, the ISP must contact the company Compliance for pre-approval. Otherwise, the use of such information in unauthorized.</span></p>
                <p><strong><u><span >Media Inquiries</span></u></strong></p>
                <p><span >ISP must refer all media inquiries regarding eaconomy™ to the eaconomy™ Compliance Department. This will ensure that accurate and consistent information reaches the general public.</span></p>
                <p><strong><u><span >Trademarks and Copyrights</span></u></strong></p>
                <p><span >An ISP may not use the eaconomy™ trademark or trade name or corporate logo to promote their independent business. Rather, they must use the "Independent Software Partner" logo to promote their business. A reproducible copy of the logo can be obtained from eaconomy™. However, this logo may only be used on personal stationery and speciﬁcally approved literature but not on clothing, signage, or motor vehicles (unless pre-approved by company Compliance). ISP may describe themselves as an "eaconomy™ Independent Software Partner" in the business pages of ofﬂine and online telephone directories. ISP should not answer the telephone in any manner that might indicate or suggest that the caller has reached an eaconomy™ corporate ofﬁce. ISP may not record or reproduce materials from any company corporate function, event, speech, etc. (unless pre-approved by company Compliance). ISP may not record, reproduce, or copy any presentation or speech by any company spokesperson, representative, speaker, ofﬁcer, director, or other ISP. ISP may not reproduce or copy any recording of a company-produced media presentation including audiotapes, videotapes, CDs, etc. ISP may not publish, or cause to be published, in any written or electronic media, the name, photograph or likeness, copyrighted materials, or property of individual Independent Software Partners with the company without express written authorization from the individual and/or company. Independent Software Partners may not publish, or cause to be published, in any written form or electronic media, the copyrighted materials or property of the company, without express written authorization from the company.</span></p>
                <p><strong><u><span >Use of Independent Software Partner's Name, Likeness, and Image</span></u></strong></p>
                <p><span >Independent Software Partner's consents to the company's use of his/her name, testimonial (or other statements about the company, its products or opportunity in printed or recorded form, including translations, paraphrases, and electronic reproductions of the same), and image or likeness (as produced or recorded in photographic, digital, electronic, video or ﬁlm media) in connection with advertising, promoting and publicizing the eaconomy™ opportunity or products, or any company related or -sponsored events. Independent Software Partners claims and Representations.</span></p>
                <p><strong><u><span >Trading Proﬁt Claims</span></u></strong></p>
                <p><span >ISP must not make claims that eaconomy's software will produce any guarantee proﬁts of any kind. There are many variables which affect the performance of the software such as market conditions, ﬁat currency volatility, day and time of the trade, just to mention of few variables. Thus there is no way to predict trading software results. You can only mention performance characteristics as contained in ofﬁcial eaconomy literature.</span></p>
                <p><strong><u><span >Income Claims</span></u></strong></p>
                <p><span >ISP's may not make income projections or claims or disclose their eaconomy income (including the showing of checks, copies of checks, bank statements, or trading results) when presenting or discussing the eaconomy opportunity or Rewards Plan, except as set forth in ofﬁcial eaconomy literature.</span></p>
                <p><strong><u><span >Unauthorized Recruiting</span></u></strong></p>
                <p><span >As an independent contractor, ISP's may participate in other direct selling or network marketing or multi-level marketing ventures (collectively, "multi-level marketing"), and ISP's may engage in selling activities related to non-eaconomy products and services if they desire to do so. Although an ISP may elect to participate in another multi-level marketing opportunity, he/she is prohibited from unauthorized recruiting activities, which include the following: recruiting or enrolling eaconomy customers or ISP's for other multi-level marketing business ventures, either directly or through a third party. This includes, but is not limited to, presenting or assisting in the presentation of other multi-level marketing business ventures to any eaconomy Customer or ISP, or implicitly or explicitly encouraging any eaconomy Customer or ISP to join other business ventures. It is a violation of this policy to recruit or enroll a eaconomy Customer or ISP for another multi-level marketing business, even if the ISP does not know that the prospect is also an eaconomy Customer or ISP; producing any literature, tapes, or promotional material of any nature for another multi-level marketing business which is used by the ISP or any third person to recruit eaconomy Customers or ISP for that business venture; selling, offering to sell, or promoting any competing products or services to eaconomy Customers or ISP. The only exception to this rule is that direct customer and personal enrollees of the ISP can be exposed to a product or service (ﬁrst level, personally sponsored only). eaconomy may cancel the ISP's agreement for violations to this provision. In addition, when an ISP participates in other multi-level marketing ventures, the ISP may not participate in any eaconomy leadership meetings, conferences, qualiﬁcation seminars, and the like.</span></p>
                <p><strong><u><span >Post-cancellation Solicitation Prohibited</span></u></strong></p>
                <p><span >A former ISP shall not directly or through a third party solicit any ISP or Customer to enroll in any direct sales, network marketing, or multi-level marketing program or opportunity for a period of one (1) year after the cancellation of an individual or entity's ISP User Agreement. This provision shall survive the expiration of the ISP obligations to eaconomy, pursuant to the ISP User Agreement.</span></p>
                <p><strong><u><span >Downline Genealogy Reports</span></u></strong></p>
                <p><span >The eaconomy Downline Genealogy Reports are conﬁdential and contain proprietary business trade secrets. An ISP may not use the reports for any purpose other than for developing their eaconomy business. During any term of the ISP User Agreement and for a period of ﬁve (5) years after the termination or expiration of the ISP User Agreement between Independent Sales Associate and eaconomy, for any reason whatsoever, an ISP shall not, on his/her own behalf or on behalf of any other person, partnership, association, corporation, or other entity: disclose any information contained in the reports to any third party; use the reports to compete with eaconomy or recruit or solicit any ISP or Customer listed on the reports to participate in other multilevel marketing ventures. This provision shall survive the termination or expiration of this Agreement.</span></p>
                <p><strong><u><span >Corporation, Partnerships, and Trusts</span></u></strong></p>
                <p><span >A corporation, partnership, or trust (collectively referred to in this section as an "Entity") may apply to be an ISP by submitting its Certiﬁcate of Incorporation, Partnership Agreement, or trust documents (these documents are collectively referred to as the "Entity Documents") to eaconomy along with a properly completed Corporation, Partnership DBA Registration Form. An ISP may change its status under the same sponsor from an individual to a partnership, corporation, or trust, or from one type of entity to another. To do so, the ISP must provide the entity documents and a properly completed ISP Agreement and the appropriate registration form. The Corporation, Partnership DBA Registration Form must be signed by all of the directors, shareholders, partners, trustees, or other individuals having an ownership interest in the business. Members of the entity are jointly and severally liable for any indebtedness or other obligations to eaconomy. As set forth herein, individual may participate directly or indirectly in more than one ISP but must be enrolled by the same sponsor. It is the responsibility of those persons involved in the Entity to conform to the laws of the state in which their Entity is formed. eaconomy reserves the right to approve or disapprove any Independent Sales Associate Application and Agreement submitted by an Entity. For the purpose of recognition and rewards, eaconomy will only recognize a maximum of two persons in the Entity. The Entity must nominate each year, at its Independent Sales Associate renewal time, the two nominees who may be the recipients of any recognition, rewards, trips, and the like which the entity becomes entitled to participate in.</span></p>
                <p><strong><u><span >Deceptive Practices</span></u></strong></p>
                <p><span >ISP must fairly and truthfully explain the eaconomy products, opportunity, Rewards Plan, and Terms and Conditions to prospective ISP's. This includes: Being honest and thorough in presenting material from the eaconomy Rewards Plan to all potential ISP's; making clear that income from the eaconomy Rewards Plan is based on software sales and not merely on sponsoring other ISP's; ISP shall not make trading proﬁt claims; making estimates of proﬁt that are based on reasonable predictions for what an average ISP would achieve in normal circumstances; representing that past earnings in a given set of circumstances do not necessarily reﬂect future earnings; not misrepresenting the amount of expenditure that an average ISP might incur in carrying on the business; not misrepresenting the amount of time an average ISP would have to devote to the business to achieve the proﬁt estimated, and not stating that proﬁts or earnings are guaranteed for any individual ISP; never stating or inferring that you will build a downline organization for anyone else; never stating that proﬁts or earnings are guaranteed for an individual ISP; and never stating that any consumer, business, or government agency has approved or endorsed the eaconomy products or its Rewards Plan.</span></p>
                <p><strong><u><span >Independent Contractor Status</span></u></strong></p>
                <p><span >ISP's are independent contractors and are not purchasers of a franchise or business opportunity. The agreement between eaconomy and its ISP does not create an employer/employee relationship, agency, partnership, or joint venture between the Company and the ISP. All ISP's are responsible for paying their own income and employment taxes. ISP will not be treated as employees for any purpose including, but not limited to, workers compensation, superannuation, or insurance. Each ISP is encouraged to establish his/her own goals, hours, and methods of sale, so long as he/she complies with applicable laws and the terms and conditions of the ISP User Agreement.</span></p>
                <p><strong><u><span >International</span></u></strong></p>
                <p><span >ISP may sell and promote eaconomy's software products, opportunity, and services or recruit or enroll any potential ISP or customer only in countries in which eaconomy is approved for business, as announced in ofﬁcial eaconomy communications. If an ISP desires to conduct business in an authorized country other than the one in which they are an ISP, he/ she must comply with all the applicable laws and regulations for that country. Adherence to Laws and Ordinances - You must obey all laws that apply to your business in all jurisdictions and Countries you are conducting eaconomy business.</span></p>
                <p><strong><u><span >One ISP per Account</span></u></strong></p>
                <p><span >An ISP may operate, receive compensation from, or have an ownership interest, legal or equitable, as a sole proprietorship, partner, shareholder, trustee, or beneﬁciary, in only one ISP account. However, notwithstanding this rule, your spouse and their children who are of legal age may become an ISP and operate their individual ISP's as long your spouse and family member's ISP accounts are placed below one of your ISP accounts and not in a cross line sales organization. The ISP accounts must be a bona ﬁde ISP that is operated by the person listed on the agreement and not by the owner of the ﬁrst ISP. ISP shall not use business entities, trusts, or other devices to avoid this policy. An exception to this policy will be considered on a case-by-case basis if two ISP marry or in cases of an ISP receiving an interest in another ISP account through inheritance from an immediate family member. Requests for exceptions to this policy must be submitted in writing to the Compliance Department. <a href="mailto:compliance@eaconomy.com">compliance@eaconomy.com</a></span></p>
                <p><strong><u><span >Sale, Transfer, or Assignment of ISP</span></u></strong></p>
                <p><span >An ISP may not sell, transfer, or assign their ISP rights to any person or entity without eaconomy's express written approval. To obtain approval, you must: be an ISP in good standing as determined by eaconomy in its sole discretion; before any transfer will be approved by eaconomy, any debt obligations the selling ISP has with eaconomy must be satisﬁed; the transferring ISP must be in good standing and not in violation of any of the terms of the ISP User Agreement or these Terms and Conditions, to transfer his/ her ISP; the combining of ISP is not permitted. eaconomy will not approve the transfer of an ISP to any individual or Entity that is a current ISP or who has an ownership interest in any ISP. Similarly, eaconomy will not approve the transfer of an ISP to any individual or Entity that has previously had any ownership interest in or operated, an ISP; no individual Business Centers may be transferred separately from the ISP. If an ISP wishes to transfer his/her ISP account, all Business Centers must be included in the transfer; the transferring ISP must notify the eaconomy Compliance Department of his/her intent to transfer the ISP account by completing and submitting a signed Transfer of ISP and ISP Application Form. No changes in the line of sponsorship can result from the transfer of an ISP; the transferee must be eligible to become an ISP and be acceptable to eaconomy in every respect.</span></p>
                <p><strong><u><span >Separation of an ISP</span></u></strong></p>
                <p><span >If ISP's wish to dissolve their jointly held ISP, they must do so in such a way as to not disturb the income or interests of their Upline and Downline Organizations. ISP should consider the following when deciding whether or not to dissolve a jointly held ISP: if a jointly owned ISP is dissolved, any one of the joint owners may operate the ISP, but the other joint owners must relinquish their rights to, and interests in, the ISP; eaconomy cannot divide a Downline Organization, nor can it split commission or bonus checks between the joint owners; if a jointly owned ISP is dissolved, the individual(s) who relinquished ownership in the original ISP may apply as new ISP under any Sponsor but may not purchase or join an existing ISP.</span></p>
                <p><strong><u><span >Succession</span></u></strong></p>
                <p><span >If an ISP dies or becomes incapacitated, his/her rights to commissions, bonuses, and Downline Organization, together with all ISP responsibilities, will pass to his/her successor(s). Upon death or incapacitation, the successor(s) must present the eaconomy Compliance Department with proof of death or incapacitation, along with proof of successions, such as a Grant of Probate or an Enduring Power of Attorney, and a properly completed ISP Application and Agreement. You may inherit and retain another ISP even though you currently own or operate an ISP.</span></p>
                <p><strong><u><span >Taxes</span></u></strong></p>
                <p><span >ISP must comply with all relevant taxation legislation. ISP should seek professional advice from their own accountant or tax advisor as to how to keep proper business records and account for tax aspects of their independent business. ISP's eaconomy income may be subject to income tax and so must be properly accounted for in annual income tax returns. ISP's conducting their eaconomy business in a businesslike manner may also be entitled to deduct certain expenses incurred in earning their eaconomy income. Such expenses should be properly recorded and evidenced by receipts.</span></p>
                <p><strong><u><span >Telephone and Email Solicitation</span></u></strong></p>
                <p><span >The use of any automated telephone solicitation equipment in connection with the marketing or promotion of eaconomy, its products, or the eaconomy opportunity is strictly prohibited. The use telemarketing operations to sell software products or services over the telephone, or to recruit ISP's, is strictly prohibited.</span></p>
                <p><span >ISP's are also forbidden from sending unsolicited e-mail messages or "spamming" to sell products or to recruit ISP. All ISPs should also make themselves familiar with relevant privacy legislation.</span></p>
                <p><strong><u><span >Territories</span></u></strong></p>
                <p><span >There are no exclusive territories for marketing eaconomy software products or services, nor shall any ISP imply or state that he/she has an exclusive territory to market eaconomy products or services.</span></p>
                <p><strong><u><span >Trade Shows and Expositions</span></u></strong></p>
                <p><span >ISP may display and/or sell eaconomy products at trade shows and expositions, but may not display or sell eaconomy products at swap meets, garage sales, ﬂea markets, or farmers' markets as these events are not conducive to the image eaconomy wishes to portray. eaconomy cannot supply inventory on consignment to ISP operating stands at such events. All literature displayed at the event must be ofﬁcial eaconomy literature and must clearly identify the individual(s) as Independent Software Partners.</span></p>
                <p><strong><u><span >Transfer of Sponsorship Conﬂicting Enrollments</span></u></strong></p>
                <p><span >Every prospective ISP has the ultimate right to choose his/her own Sponsor. As a general rule, the ﬁrst ISP who does meaningful work with a prospective ISP is considered to have a ﬁrst claim to sponsorship. Basic tenets of common sense and consideration should govern any dispute that may arise. In the event that a prospective ISP or any ISP on behalf of a prospective ISP, submit more than one ISP Application and Agreement to eaconomy, listing a different Sponsor on each, the Company will only consider valid the ﬁrst ISP Application and Agreement that it receives, accepts, and processes. If there is any question concerning the sponsorship of an ISP, the ﬁnal decision will be made by eaconomy.</span></p>
                <p><strong><u><span >Change of Sponsorship and Cross-line recruiting</span></u></strong></p>
                <p><span >eaconomy will not permit any change in the line of sponsorship except in the following circumstances: where an ISP has been fraudulently or unethically induced into joining. If you terminate your ISP in writing you may rejoin under the Sponsor of your choice after a period of twelve (12) months; following termination of your ISP, you may participate as a Customer during the&nbsp;twelve (12) month period. In the event you terminate your ISP, you forfeit all rights, bonuses, and commissions under your previous line of sponsoring. You may not avoid compliance with this policy through the use of DBAs, assumed names, corporations, partnerships, trusts, spouse names, ﬁctitious ID numbers, etc. If you have been "inactive" (i.e., no purchases or sales of eaconomy products or participation in any other form as an ISP) for a period of twelve (12) successive months, you may terminate your ISP in writing and rejoin immediately under the Sponsor of your choice. Cross-line raiding is strictly prohibited. "Cross-line raiding" is deﬁned as the enrollment or attempted enrollment of an individual or Entity that already has a current ISP User Agreement on ISA with eaconomy, or who has had such agreement within the preceding six (6) calendar months within a different line of sponsorship. The use of trade names, DBAs, assumed names, corporations, partnerships, trusts, spouse names, ﬁctitious ID numbers or any other vehicle to circumvent this policy is prohibited. ISP may not demean, discredit, or invalidate other ISP in an attempt to entice another Independent Sales Associate to become part of the ﬁrst ISP's Downline Organization.</span></p>
                <p><strong><u><span >Responsibilities of Independent Software Partners and Sponsors Ongoing Supervision, Training, and Sales</span></u></strong></p>
                <p><span >Any ISP who sponsors another ISP into eaconomy must train the new ISP in product knowledge, effective sales techniques, the Rewards Plan, and the Terms and Conditions. ISP must also supervise and monitor ISP in their Downline Organization to ensure they conduct business professionally and ethically, promote sales properly, and provide quality customer service. As an ISP progresses through the various levels of leadership, his/her responsibilities to train and motivate downline ISP will increase.</span></p>
                <p><strong><u><span >Non-Disparagement</span></u></strong></p>
                <p><span >In setting the proper example for their downline, ISP must not disparage other ISP, CWE's Products, the Rewards Plan, or the Company's employees. Such disparagement constitutes a material breach of these Terms and Conditions. Holding Applications or Orders - All ISP must forward to eaconomy any forms and applications they receive from other ISP or applicant ISP, or Customers or applicant Customers, on the next business day after which the forms or applications are signed.</span></p>
                <p><strong><u><span >Reporting Policy Violations</span></u></strong></p>
                <p><span >ISP should report any observed violations of a policy violation to the eaconomy Compliance Department.</span></p>
                <p><strong><u><span >Bonuses and Commissions Bonus and Commission Cycles</span></u></strong></p>
                <p><span >eaconomy pays commissions on a daily, weekly and monthly cycles to the ISP's Account located in the ISP Back Ofﬁce. An ISP must review his/her commissions and report any errors or discrepancies to eaconomy within ten (10) days from the date of the commission payment. Errors or discrepancies which are not brought to eaconomy's attention within the 10 day period will be deemed waived by the ISP.</span></p>
                <p><strong><u><span >Adjustment of Bonuses and Commissions</span></u></strong></p>
                <p><span >ISP's earn commissions and bonuses based on software product sales to End Consumers. Accordingly, eaconomy will adjust commissions and bonuses earned from any sale when the ISP or any other End Consumer returns the sold software product for a refund. eaconomy will deduct the sales volume (PV) attributable to the returned product from the Upline ISP's group volume within the ﬁrst two (2) weeks after the refund is given.</span></p>
                <p><strong><u><span >Loss of Rights to Commissions</span></u></strong></p>
                <p><span >You must be an active ISP and in compliance with the terms of the Independent Software Partner User Agreement to qualify for commissions and bonuses.</span></p>
                <p><strong><u><span >Unclaimed Commissions</span></u></strong></p>
                <p><span >ISP who provide eaconomy with incomplete or invalid bank account information will have their commission and bonus retained as a credit. Any unclaimed credit will be held in trust for 12 months, during which time eaconomy may periodically notify the ISP in writing of their credit balance.</span></p>
                <p><strong><u><span >Dispute Resolution and Disciplinary Proceedings between Independent Sales Associates Grievances and Complaints</span></u></strong></p>
                <p><span >When an Independent Sales Associate has a grievance or complaint with another Independent Sales Associate regarding any practice or conduct in relationship to their respective eaconomy businesses, the complaining Independent Sales Associate should ﬁrst discuss the problem with the other Independent Sales Associate. If this does not resolve the problem, the complaining Independent Sales Associate should report the problem to his/ her upline to resolve the issue at a local level. If the matter cannot be resolved, it must be reported in writing to the eaconomy Compliance Department. The Compliance Department will review the complaint and make a ﬁnal decision. The complaint should identify speciﬁc instances of alleged improper conduct and, to the extent possible, identify the relevant dates on which the event(s) complained of took place, the location(s) where they occurred, and all persons who have ﬁrsthand knowledge of the improper conduct.</span></p>
                <p><strong><u><span >Compliance Department Review</span></u></strong></p>
                <p><span >Upon receipt of a written complaint, the eaconomy Compliance Department will investigate the matter, review the applicable policies, and render a decision on how the dispute shall be resolved. The Compliance Department may also issue disciplinary sanctions consistent with the provisions of this Agreement Disputes between eaconomy and Independent Sales Associates.</span></p>
                <p><strong><u><span >Mediation and arbitration</span></u></strong></p>
                <p><span >All unresolved disputes and claims relating to eaconomy, its Rewards Plan, its Products, the rights and obligations of its ISP and eaconomy, or any other claim or cause of action relating to product purchase(s) or performance, either of an ISP or of eaconomy under the Independent Software Partner User Agreement, shall ﬁrst be put before a mediator acceptable to both parties for resolution. Each party shall bear its own costs in the mediation. Should mediation fail to resolve the dispute then it shall be put before arbitration in Clovis, California, USA. Each party to the arbitration shall be responsible for their own costs, including legal and ﬁling fees. This agreement to mediate and, failing mediation, arbitrate will survive any cancellation or expiration of the Independent Software Partner User Agreement. Nothing in these Terms and Conditions shall prevent eaconomy from applying to and obtaining from any court having jurisdiction a writ of attachment, temporary injunction, preliminary injunction, permanent injunction, or other available relief to safeguard and protect eaconomy's interest prior to, during, or following the ﬁling of any arbitration or another proceeding, or pending the rendering of a decision or award in connection with any arbitration or other proceeding. The existence of any ISP claim or cause of action against eaconomy does not preclude eaconomy from enforcing the ISP's covenants and agreements contained in the Independent Software Partner User Agreement.</span></p>
                <p><strong><u><span >Jurisdiction, Venue, and Choice of Law</span></u></strong></p>
                <p><span >The jurisdiction and venue of any matter pursuant to this agreement shall reside in Clovis, California, USA.</span></p>
                <p><strong><u><span >Disciplinary Actions</span></u></strong></p>
                <p><span >Violation of any of the terms and conditions of the Independent Software Partner User Agreement, or any illegal, fraudulent, deceptive, or unethical business conduct by an ISP, may result at eaconomy's discretion, in one or more of the following sanctions: a written warning, clarifying the meaning and application of a speciﬁc policy or procedure, and advising that a continued breach will result in further sanctions; probation, which may include requiring an ISP to take remedial action and will include follow-up monitoring by eaconomy to ensure compliance with the Agreement; withdrawal or denial of an award or recognition, or restricting participation in eaconomy-sponsored events for a speciﬁed period of time or until the ISP satisﬁes certain speciﬁed conditions; suspension of certain privileges of ISP, including but not limited to placing a software product order, participating in eaconomy programs, progressing in the Rewards Plan, or participating as a Sponsor (including participating as an International Sponsor), for a speciﬁed period of time or until the ISP satisﬁes certain speciﬁed conditions; withholding commissions or bonuses for a speciﬁed period of time or until the ISP satisﬁes certain speciﬁed conditions; imposing fair and reasonable ﬁnes or other penalties in proportion to actual damages incurred by eaconomy and as permitted by law; and/or terminating an ISP.</span></p>
                <p><strong><u><span >Independent Software Partner Services Changes to the ISP</span></u></strong></p>
                <p><span >Each ISP must immediately notify eaconomy of all changes to the information contained on the Independent Software Partner Application and Agreement. ISP may modify their existing Independent Software Partner User Agreement by submitting a written request, a properly executed Independent Software Partner User Agreement, and appropriate supporting documentation. Certain changes can be made by the ISP in the ISP's Back Ofﬁce.</span></p>
                <p><strong><u><span >Addition of Co-applicants</span></u></strong></p>
                <p><span >When adding a co-applicant to an existing ISP, eaconomy requires both a written request and a properly completed Independent Software Partner User Agreement containing the applicant's and co- applicant's signatures. The modiﬁcations permitted within the scope of this paragraph do not include a change of sponsorship.</span></p>
                <p><strong><u><span >Commission Statements/tax Invoices</span></u></strong></p>
                <p><span >Commission Statements/Tax Invoices are provided for all active ISP's receiving a commission in your ISP Back Ofﬁce.</span></p>
                <p><strong><u><span >Errors or Questions</span></u></strong></p>
                <p><span >In the event an ISP has questions about or believes that any errors have been made regarding commissions, bonuses, Downline Genealogy Reports, orders, or charges, the ISP must notify eaconomy within thirty (30) days of the date of the purported error or incident in question. eaconomy will not be responsible for any error, omission, or problem not reported within ten (10) days.</span></p>
                <p><strong><u><span >Resolving Problems</span></u></strong></p>
                <p><span >If you have any questions regarding shipments, orders, commissions and bonuses, or the Rewards Plan, please message eaconomy Support Services in your ISP Back Ofﬁce.</span></p>
                <p><strong><u><span >Inactivity and Cancellation Policies</span></u></strong></p>
                <p><span >ISP who do not meet the Active Status requirements speciﬁed in the eaconomy Rewards Plan may not receive a commission and may lose accumulated Sales Volume (PV) for the sales generated through their Downline Organization.</span></p>
                <p><strong><u><span >Involuntary Cancellation</span></u></strong></p>
                <p><span >An ISP's violation of any of the terms of the Independent Software Partner User Agreement, including any amendments which may be made by eaconomy in its sole discretion from time to time,
                 constitutes a material breach of the Independent Software Partner User Agreement and may result at eaconomy's option, in any of the Disciplinary Actions listed herein, 
                 including cancellation of his/her ISP. Involuntary Cancellation of an ISP will result in the ISP's loss of all rights to his/her Downline Organization and any bonuses and 
                 commissions generated thereby. An ISP whose Agreement is involuntarily canceled shall receive commissions and bonuses only for the last full calendar week prior to termination. 
                 When an ISP is involuntarily canceled, the ISP will be notiﬁed by certiﬁed mail at the address on ﬁle with the Company or email on ﬁle. Cancellation is effective on the date on which 
                 written notice is mailed via certiﬁed mail, return receipt requested, to the Independent Software Partner's last known address or when the ISP receives actual notice of cancellation, 
                 whichever occurs ﬁrst or the date and time the email was sent. In the event of such Involuntary Cancellation, the Independent Software Partner must immediately cease to represent himself/herself 
                 as an ISP. The ISP may appeal the termination to the eaconomy Compliance Department. The ISP's appeal must be in writing and must be received by the company within ﬁfteen (15) 
                 calendar days of the date of eaconomy’s cancellation letter. If eaconomy does not receive the appeal within the ﬁfteen-day period, the cancellation will be ﬁnal. The ISP must submit all 
                 supporting documentation with his/ her appeal correspondence. The written appeal will be reviewed by the Compliance Department. If the ISP ﬁles a timely appeal of termination, the Compliance 
                 Department will review and reconsider the termination, consider any other appropriate action, and notify the ISP in writing of its decision. This decision of the Compliance Department will be ﬁnal. 
                 An ISP whose Independent Software Partner User Agreement is involuntarily canceled may re-apply to become an ISP twelve (12) calendar months from the date of cancellation. Any such ISP wishing to 
                 re-apply must submit a letter to the eaconomy Compliance Department setting forth the reasons why he/she believes eaconomy should allow him or her to operate an ISP. It is within eaconomy's sole 
                 discretion whether to permit such an individual to again operate an eaconomy business.</span></p>
                <p><strong><u><span >Written Cancellation</span></u></strong></p>
                <p><span >An ISP may cancel his/her Agreement with eaconomy at any time and for any reason by providing written notice or email to eaconomy indicating his/her intent to discontinue his/her ISP status. The written notice or email must include the ISP's signature, printed name, address, and appropriate identiﬁcation number.</span></p>
                <p><strong><u><span >Effect of Cancellation</span></u></strong></p>
                <p><span >Following an ISP's voluntary or involuntary cancellation, such former ISP shall have no right, title, claim, or interest to the Downline Organization which he/ she operated or any bonus and/or commission from the sales generated by the organization. Following an ISP's voluntary or involuntary cancellation, the former ISP shall not hold himself or herself out as an Independent Software Partner shall not have the right to sell eaconomy software products or services, must remove any eaconomy sign from public view, and must discontinue using any other materials bearing any eaconomy logo, trademark, or service mark. An ISP who is voluntarily canceled will receive commissions and bonuses only for the last full calendar week prior to his/her cancellation. An ISP whose Agreement is involuntarily canceled will receive commissions and bonuses only for the last full calendar week prior to cancellation unless monies were withheld by the Company during an investigation period. If an investigation of the ISP's conduct results in his/ her involuntary cancellation, he/she shall not be entitled to recover withheld commissions and bonuses.</span></p>
                <p><strong><u><span >Definitions</span></u></strong></p>
                <p><span >Active ISP - An ISP who is trading ﬁat currency using eaconomy's software on a daily basis as set forth in the eaconomy Rewards Plan. </span></p>
                <p><span >ISP - An individual who has executed an Independent Software Partner User Application and Agreement which has been accepted by eaconomy. ISP's are required to meet certain qualiﬁcations and are responsible for the training, motivation, support, and development of the ISP's in their respective Downline Organizations. ISP is entitled to purchase eaconomy software products at ISP prices, enroll Customers and new ISP's, and take part in all Company ISP programs. </span></p>
                <p><span >ISP User Agreement - The term Independent Software Partner User Agreement, as used in the Terms and Conditions, refers to the Independent Software Partner Application and Agreement, eaconomy's Terms and Conditions, and the Rewards Plan. </span></p>
                <p><span >Cancellation - Termination of an individual's ISP. </span></p>
                <p><span >Cancellation may be either voluntary or Involuntary Cancellation - Termination of an ISP which is initiated by eaconomy. </span></p>
                <p><span >Voluntary Cancellation - The termination of an ISP instituted by the ISP who elects to discontinue his/her afﬁliation with eaconomy for any reason. </span></p>
                <p><span >Downline Organization - An ISP's downline Organization consists of all ISP below him/her. </span></p>
                <p><span >Genealogy Report - A report generated by eaconomy that provides critical data relating to the identities of ISP and sales information of each ISP's Downline Organization. This report contains proprietary trade secret information. </span></p>
                <p><span >Immediate Household - An ISP, his or her spouse or de-facto, and dependents. </span></p>
                <p><span >Level - The layers of downline ISP's in a particular ISP's downline Organization. This term refers to the relationship of an ISP relative to a particular upline ISP, determined by the number of ISPs between them who are related by sponsorship. </span></p>
                <p><span >Ofﬁcial eaconomy Material - Literature, audio or videotapes, and other materials developed, printed, published, or distributed by eaconomy. </span></p>
                <p><span >Sponsor - An ISP who enrolls a new ISP or Customer and is listed as the Sponsor on the Independent Software Partner User Application and Agreement. As the term implies, the Sponsor has a responsibility to assist those he/she brings into the business. </span></p>
                <p><span >Upline - The term refers to the ISP or ISP's above a particular ISP in a sponsorship line to the company. Conversely stated, it is the line of Sponsors that links any particular ISP to the Company.</span></p>
              

                
                
            </div>

        </div>
    </Layout>
  );
};

export default TermsAndConditions;
