import React from 'react';
import Layout from './../components/Layout';
import '../scss/pages/UserAgreement.scss';

const UserAgreement = () => {

   
  return (
    <Layout>
        <div className="user-agreement-page">
            <div className='content-div'>
                <h2>User Agreement</h2>               
                   
                <p><span >Independent Software Partners (hereinafter referred to as ISP) Terms and Conditions Agreement (User Agreement) between the named APPLICANT (hereafter APPLICANT) and eaconomy™. (hereafter the company) effective under the terms and conditions below: APPLICANT hereby applies for authorization as an ISP in the company's network marketing program. For a period of 21 days from the submission of this application, or until such time as the company notiﬁes APPLICANT of this application's acceptance or rejection, APPLICANT is provisionally authorized as an ISP and granted the rights to sell the company software products and services. the company reserves the right to accept or reject any application for any reason.</span></p>
                <p><span >Upon acceptance as an ISP by the company, APPLICANT is authorized as an ISP for 30 days from the day of enrollment. The Company reserves the right to terminate this Agreement at any time if the Company elects to: (1) cease business operations; (2) dissolve as a business entity; or (3) terminate distribution of its software products and/or services via direct selling channels, or at any time upon not less than 7 days' notice and without further notice if the ISP breaches this User Agreement and fails to remedy the breach before the end of the notice period.</span></p>
                <p><span >APPLICANT has read and agrees to be bound by the terms of this agreement, the company's full Compensation Plan, Policies &amp; Procedures, Income Disclaimers, Independent Software Partners Agreement, Terms of Use, Privacy Policy, Spam Policy and Refund Policy, all of which are incorporated herein by reference and made a part hereof for all purposes. The company reserves the right to change the Compensation Plan, Policies &amp; Procedures, Income Disclaimers, Independent Software Partners Agreement,Terms of Use, Privacy Policy, Spam Policy and Refund Policy at any time in its sole discretion, and APPLICANT agrees to be bound by such changes.</span></p>
                <p><span >APPLICANT is an independent contractor under the terms of this agreement, and not an agent, employee, or legal representative of his/ her sponsor or the company, and will in no way represent him/herself as such. As such, APPLICANT has no power to bind the company to any obligation and APPLICANT is responsible for all applicable income, sales, social security, unemployment or other tax, license, or fee arising out of APPLICANT's activities hereunder.</span></p>
                <p><span >APPLICANT will not produce, promote, or use materials of any kind describing the company's names, programs, products, and trademarked, copyrighted, or otherwise protected materials except as permitted in the company's policies.</span></p>
                <p><span >APPLICANT has the duty to supervise and train any ISPs that he/she may sponsor as described in the Terms and Conditions. APPLICANT will explain the company's programs honestly and completely when presenting them to others.</span></p>
                <p><span >APPLICANT understands and will make clear in any presentation the following: that no earnings and/or exchange trading proﬁts are guaranteed by the company or its programs; no ISP will earn money solely for sponsoring; no speciﬁc amount of software product that must be purchased at any level; commissions are based on software product and service sales; that there are no exclusive territories for ISPs in the program.</span></p>
                <p><span >APPLICANT agrees that compensation is only paid for sales of software product as deﬁned in the Terms and Conditions and in the company's Rewards Plan. </span></p>
                <p><span >Any sale or assignment of this agreement must be approved by the company. Successors in interest or assignments must comply with all program requirements.</span></p>
                <p><span >The undersigned hereby acknowledges that he/she is of legal age and authorized to bind APPLICANT to each of the terms set forth herein and to the terms of the Policies &amp; Procedures.</span></p>
                <p><span >Venue and jurisdiction for any action pertaining to this agreement or any disagreement or claim between the parties hereto shall be governed by the laws of The State of Nevada in the County of Clark.</span></p>
                <p><span >No purchase or investment is necessary to become an ISP.</span></p>
                <p><span >You have the right to cancel your ISP agreement at any time and for any reason.</span></p>
                <p><span >You are free to participate in other multilevel marketing ventures, but you may not sell or promote to other eaconomy™ ISPs or Customers similar or competitive products or services or any other multilevel marketing opportunity, except for your direct enrollees in your eaconomy™ business.</span></p>
                <p><span >The company's genealogy reports are conﬁdential and proprietary business trade secrets. You may not use the reports for any purpose other than to develop your eaconomy™ business. Speciﬁcally, you must not disclose any information contained in the reports to a third party or use the reports to compete with the company or to recruit or solicit other ISPs or Customers to participate in other multilevel marketing ventures. </span></p>
                <p><span >the company's failure to exercise any rights as set forth in this agreement or to insist on your strict compliance with the terms and conditions of this User Agreement and the Policies &amp; Procedures does not constitute a waiver of the company's right to require compliance therewith.</span></p>
                <p><span >the company's waiver of any ISP default does not affect the company's rights with respect to any subsequent default or the rights or obligations of any other ISP. Delays or omissions by the company in exercising rights which might arise from a Partner's default do not affect the company's rights concerning the default or any subsequent default.</span></p>
                <p><span >the company reserves the right to cancel any ISP at any time for cause if the ISP violates the terms and conditions of this Agreement or the provisions of the Policies &amp; Procedures and Rewards Plan.</span></p>
                <p><span >Taxpayer Identiﬁcation Number. If you are a United States person (including a resident alien), you must provide the company with your correct taxpayer identiﬁcation number ("TIN"), which for individuals is either your Social Security Number ("SSN") or, if you are a resident alien and you do not have and are not eligible to get an SSN, your Individual Taxpayer IdentiﬁcationNumber ("ITIN"). For a distributorship that is a partnership, corporation, company or association organized in the United States or under the laws of the United States, you must provide the company with your employer Identiﬁcation Number ("EIN"). If you fail to provide the company with a TIN or the TIN you provide to the company is incorrect, the company will withhold and pay to the IRS 28 percent of your income over $600, unless you certify to the company that you are a corporation exempt from backup withholding or otherwise not subject to backup withholding. By signing this Agreement, you certify that (i) the TIN you have provided to the company is correct, (ii) you are a United States person (including a resident alien), (iii) if applicable, you are not subject to backup withholding, and (iv) you are exempt from the requirement to report foreign ﬁnancial assets under the Foreign Account Tax Compliance Act ("FATCA").</span></p>
                <p><span >You may be required from time to time to provide the company with personal information relating to your ISP Agreement. The company's rights to use your personal information and your rights to access and correct the personal information you give the company are described in the company's Policies &amp; Procedures. By signing this Agreement, you consent to the company's collection, use, and disclosure of your personal information in accordance with the company's Policies &amp; Procedures.</span></p>
                <p><span >By signing this Agreement, you give the company consent to contact you by telephone, facsimile transmission, e-mail or text, concerning your ISP Agreement, and any related eaconomy™ matter.</span></p>
                <p><span >ISP agrees not to contact or initiate contact at any time or for any purpose, either directly or indirectly, with any ofﬁcers, directors, shareholders, consultants, attorneys, employees, agents or other afﬁliates of the company's Vendors or Suppliers, unless such approval is speciﬁcally granted in written form by the company, which shall be considered on a case-by-case basis. Any communication sent by any ISP to the company's Vendors or Suppliers, either directly or indirectly to any ofﬁcers, directors, shareholders, consultants, attorneys, employees, agents or other afﬁliates of the company's Vendors or Suppliers is in direct violation of this ISP Agreement and could result in the termination of your ISP Agreement. This includes any and all verbal and or written communications. From time to time the company may invite guest from the company's Vendors or Suppliers to speak on company webinars and conference calls, such guest appearances do not constitute the company's approval for furthered communications with the company's Vendors or Suppliers. You further agree and understand that the only entity which has an Agreement with the company's Vendors or Suppliers is the company.</span></p>
                <p><span >To the maximum extent permitted by law, eaconomy&amp;trade, its parent or afﬁliated companies, directors, ofﬁcers, shareholders, employees, assigns, and agents (collectively referred to as "afﬁliates"), shall not be liable for, and I release eaconomy&amp;trade and it's afﬁliates from, all claims for consequential and exemplary damages for any claim or cause of action relating to the Agreement. I further agree to release eaconomy&amp;trade and it's afﬁliates from all liability arising from or relating to: (a) my, or any other ISP's, breach of the Agreement; (b) the promotion or operation of a eaconomy&amp;trade business by me or any other ISP and any activities related to it, including, but not limited to, the presentation of Products/Services or the Company Rewards Plan, the operation of a motor vehicle, the lease of meeting or training facilities, etc., and agree to indemnify eaconomy&amp;trade and its afﬁliates for any liability, damages, ﬁnes, penalties, or other; (c) any incorrect data or information provided by me or any other ISPs to eaconomy™ (d) my, or any other ISP's, failure to provide any information or data necessary for eaconomy&amp;trade to operate its business; or (e) awards arising from any unauthorized conduct that I undertake in operating my business. I further agree to indemnify eaconomy&amp;trade for any liability, damages, ﬁnes, penalties or other awards arising from any unauthorized conduct that I undertake in operating my eaconomy&amp;trade business.</span></p>
                <p><span >The Company grants to me a non-exclusive, royalty free, revocable license to use the intellectual property in the name of eaconomy™, trademarks (whether registered or unregistered), and other intellectual property rights in any materials or documents pertaining to the subject matter of this Agreement for the purpose of promoting the software products and services and sourcing potential customers. I agree that the Company may impose restrictions on my use of the company's name, trade names and trademarks, logos and other intellectual property and advertising in order to protect the rights, reputation and image of eaconomy™, provided that such restrictions are applied to all ISP's generally. I also agree to not apply singly or in association with any other party for registration of any intellectual property owned by eaconomy™ capable of registration but not registered and to give all reasonable assistance, at the company's reasonable cost, to assist eaconomy™ to register any such intellectual property.</span></p>
                <p><span >If a ISP wishes to bring an action against eaconomy™ for any act or omission relating to or arising from the Agreement, such action must be brought within 30 days from the date of the alleged conduct giving rise to the cause of action. Failure to bring such action within such time shall bear all claims against eaconomy™ for such act or omission. ISP waives all claims that any other statutes of limitations apply.</span></p>
                
            </div>

        </div>
    </Layout>
  );
};

export default UserAgreement;
